### ISSUE TITLE
can't npm download

### ISSUE THREAD

**Issue by danielxli** [saphero/sphero-hack#121]
npm install giving error and cloning from github also same error when trying to open with `npm start`.
error: 
Error: Cannot find module 'xpc-connection'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/danielli/sphero-hack/node_modules/noble/lib/mac/yosemite.js:7:21)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)

npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE
npm ERR! saphero@1.0.2 start: `node bin/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the saphero@1.0.2 start script 'node bin/index.js'.
npm ERR! This is most likely a problem with the saphero package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node bin/index.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls saphero
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/danielli/sphero-hack/npm-debug.log

**Comment by jessethach** [comment]
Hi @danielxli – do you have the latest version of xcode installed?

**Comment by arialaurel** [comment]
@danielxli This github issue may also be relevant to your problem: https://github.com/orbotix/sphero.js/issues/55

**Comment by ghost** [comment]
@danielxli Let us know if your problem persists! Otherwise closing this issue. :)
